# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Conan's Notes
author: Conan
email: conanchou1412@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Programming, Design, Music, and everything in between.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://conanblog.me" # the base hostname & protocol for your site, e.g. http://example.com
lang: zh
permalink: /blog/:year/:month/:day/:title/
twitter_username: conanchou
github_username: conanchou
# disqus:
  # shortname: conannotes
google_analytics: UA-33556525-1
sass:
  style: compressed

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-assets
  - kramdown-parser-gfm
exclude:
  - Gemfile
  - Gemfile.lock

assets:
  compress:
    js: true
    css: false
  assets:
    - "main.js"
    - "tongwen*.js"
  sources:
    - javascripts
collections:
  projects:
    output: true
    permalink: /:collection/:name
